FIX: Bring pk_ops.h and pk_ops_impl.h back as public headers
randombit/botan pull request #3879
Opened 2024-01-09 08:59 UTC by reneme

See #3878 for details.

This also adds a new example, with three objectives:

* Showcase how to integrate custom public-key algorithms
* Explain how one could use Botan to build a hybrid public-key scheme (e.g. in the transition to PQC)
* Act as a regression test for the ability of applications to build custom public-key schemes using Botan's API

2024-01-09 16:38 UTC, reneme commented
Yeah, user convenience was the only reasoning. And I actually had my doubts, because the interplay between the base-classes in `pk_ops.h` with the helpers isn't really obvious. If you're saying that it wasn't public historically either, let's just hide it again.

I can't work on that today anymore, though. Will rework this first thing tomorrow.

2024-01-10 12:44 UTC, securitykernel approved these changes

2024-01-10 20:56 UTC, randombit requested changes

2024-01-10 20:56 UTC, randombit commented on src/lib/pubkey/pk_ops.h
> +class BOTAN_PUBLIC_API(3, 3) Encryption {
These should be `BOTAN_UNSTABLE_API`.

Using this interface requires deriving, which is not covered by our current SemVer guarantee (`doc/sem_ver.rst`) and already I know we have to change at least the decryption API to support some side channel mitigations.

2024-01-11 06:33 UTC, reneme commented on src/lib/pubkey/pk_ops.h
> +class BOTAN_PUBLIC_API(3, 3) Encryption {
Done.

2024-02-15 23:03 UTC, randombit approved these changes
LGTM, thanks

2024-02-16 07:40 UTC, merged