Add IPAddrBlock and ASIdentifiers extensions (RFC 3779)
randombit/botan pull request #4443
Opened 2024-11-25 15:36 UTC by arckoor

This PR implements two extensions required for working with secure routing. These extensions contain IP Addresses or AS numbers, as specified by [RFC 3779](https://datatracker.ietf.org/doc/rfc3779/).

Both encoding and decoding of AS numbers, single addresses, address prefixes and min-max ranges have been tested.

2024-11-26 13:48 UTC, randombit commented
@arckoor There are some CI failures which are relevant. Stylistically for calls to `min`,`max` where the compiler can’t deduce `T` we prefer `std::min<T>` vs use of casts.

2024-11-27 16:07 UTC, randombit commented
@arckoor Remaining CI issues look related to the visibility annotations (eg `BOTAN_PUBLIC_API`) probably something is not being exported as a symbol.

2024-11-27 16:11 UTC, arckoor commented
@randombit We're currently chipping away at the fuzzers, but the visibility is also an issue. Previously linux/clang was failing, which I resolved by moving the definition of `set_from_bytes` to the .h file, the other errors could probably be solved by moving the rest there too, but that does not sound like a good solution to me. All of these errors are most likely related to the use of templates, though I don't know what the cleanest / recommended way to resolve them is.

2024-11-27 22:35 UTC, randombit commented
@arckoor ok thanks. I’ll try to have a look over the weekend

2024-12-20 21:02 UTC, randombit commented
@arckoor The main issue here is CI failing. In general this is a change that's appropriate to the library and the code from a quick look seems fine. But we certainly can't merge if it will break the build. Unfortunately I don't know the exact issue; I guess symbol visibility behaves differently on macOS/Windows vs Linux. My only suggestion would be to try adding `BOTAN_PUBLIC_API` macros to the various subclasses until the build succeeds.

2025-01-07 17:36 UTC, arckoor commented
@randombit The clang build should now succeed. After much debugging we realized the compiler was optimizing away the `IPAddress` class completely. We tried various things like including a dummy function that instantiates all variations at compile time, nothing helped. We worked around this issue by defining a new macro that forces compilation, the windows and macos builds are probably still going to fail, as there the compilers seems to optimize away even more. A potential workaround would be to add the forced compilation macro everywhere, or move the entire thing to `x509_ext.h`.

2025-01-09 19:21 UTC, butteronarchbtw commented
@randombit we've now resolved the symbol issues by instantiating the template classes in `x509_ext.cpp` and also did some small tweaks to fix the other checks. Does this seem like a viable solution to you?

2025-01-18 22:46 UTC, randombit requested changes
@arckoor Not a full review and I still need to check the tests but enough for you to get started on. Overall things seem fine with two exceptions

1) The various types have setters that seem to me quite easy to misuse. I would rather see values set using constructors, at least whenever possible.

2) The decoding functions seem really complicated considering the types involved. `BER_Decoder` is designed to make this easy, so either there is improvements possible in the decoding or there are improvements possible in `BER_Decoder`. I left some suggestions which are untested but should help get you going.

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.h
> +            void set_from_bytes(const std::vector<uint8_t>& v);
Input values should be `span`, here `std::span<const uint8_t> v`

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.h
> +class BOTAN_PUBLIC_API(3, 6) IPAddressBlocks final : public Certificate_Extension {
The `BOTAN_PUBLIC_API` macros should read 3, 7 since that's the next release

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.h
> +            void set_max(const IPAddress<V>& max) { m_max = max; }
General comment: I'd prefer if possible (and it seems like it is from my current understanding) that values are set once in a constructor and we don't have any setters.

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +   }
Here combine the check on `afi` and the decoding

```
if(afi == 1) {
  ...
} else if(afi == 2) {
  ...
} else {
   throw Decoding_Error("Only AFI IPv4 and IPv6 are supported.");
}
```

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +      bytes.assign(as_min_obj.data().begin(), as_min_obj.data().end());
`ASId` is just an `INTEGER`, `BER_Decoder` supports this already

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +   ASN1_Type type_tag = obj.type_tag();
I think this function can be quite a bit simpler overall, something like (untested)

```
ASN1_Tag next_tag = from.peek_next_object().type_tag();
if(next_tag == ASN1_Type::Integer) {
   from.decode(m_min);
   m_max = m_min;
} else if(next_tag == ASN11_Type::Sequence) {
  from.start_sequence().decode(m_min).decode(m_max).end_cons();
} else {
   throw ...
}
```

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +      into.add_object(ASN1_Type::Integer, ASN1_Class::Universal, encode_asnum(m_min));
`DER_Encoder` already knows to zero prefix, all that should be required here is

`into.encode(m_min)`

(likewise wherever `encode_asnum` is called, I don't believe this function is necessary at all)

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +   if(type_tag == ASN1_Type::BitString) {
This function similar to `ASBlocks::ASIdOrRange::decode_from` can be made much simpler by using `peek_next_object` to decide if you are in the `IPAddress` or `IPAddressRange` case. Then you can use the builtin functionality for decoding bit strings, parsing sequences etc without having to replicate logic here.

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +      throw Decoding_Error("AFI/SAFI too long / too short.");
I find this surpsisingly hard to parse. Maybe just

`if(addr_family.size() != 2 && addr_family.size() != 3)`

?

2025-01-18 22:46 UTC, randombit commented on src/lib/x509/x509_ext.cpp
> +   BER_Object obj = from.get_next_object();
I think this can be done as (untested)

```
from.start_sequence()
 .decode_optional(m_asnum, ASN1_Type(0), ASN1_Class::ExplicitContextSpecific);
 .decode_optional(m_rdi, ASN1_Type(1), ASN1_Class::ExplicitContextSpecific);
.end_cons()
```

If it's something much harder than that it suggests `BER_Decoder` needs a helper

2025-01-28 13:38 UTC, arckoor commented
@randombit We're currently changing some more stuff around to more rigidly conform to the RFC, so we'll let you know when the major changes are done and it makes sense to take a look again.

2025-02-19 13:07 UTC, closed without merging